# Generated by Django 5.0.6 on 2024-05-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_interest_platform_schedule_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LFGAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('meetupTime', models.DateTimeField()),
                ('currentPartyCount', models.IntegerField()),
                ('neededPartyCount', models.IntegerField()),
                ('locationCity', models.CharField(max_length=50)),
                ('locationState', models.CharField(max_length=25)),
                ('locationZip', models.CharField(max_length=7)),
                ('partySpecifics', models.TextField()),
                ('meetupAddress', models.TextField()),
                ('invitesSent', models.IntegerField()),
                ('pLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
