# Generated by Django 5.0.6 on 2024-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_lfgalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgalert',
            name='meetupTime',
        ),
    ]
