# Generated by Django 5.0.6 on 2024-05-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_lfgalert_meetuptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfgalert',
            name='currentPartyCount',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='invitesSent',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='locationCity',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='locationState',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='locationZip',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='meetupAddress',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='neededPartyCount',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='pLeader',
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='partySpecifics',
        ),
    ]
