# Generated by Django 5.0.6 on 2024-06-01 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_lfgalert_currentpartycount_lfgalert_interest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgalert',
            name='pLeader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lfgalert',
            name='interest',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='lfgalert',
            name='interest',
            field=models.ManyToManyField(related_name='lfg_alerts', to='API.interest'),
        ),
    ]
